export const data = [
 
  {
    cardType: "restaurant",
    layoutAlignmentType: "VERTICAL",
    data: {
      type: "restaurant",
      data: {
        type: "F",
        id: "408386",
        name: "NOTO - Healthy Ice Cream",
        uuid: "bc52fe9e-a888-4103-9777-16eff84516b2",
        city: "1",
        area: "Koramangla",
        totalRatingsString: "",
        cloudinaryImageId: "544f9e6dce1efb7054e4ac5d98aba049",
        cuisines: ["Ice Cream"],
        tags: [],
        costForTwo: 25000,
        costForTwoString: "₹250 FOR TWO",
        deliveryTime: 23,
        minDeliveryTime: 23,
        maxDeliveryTime: 23,
        slaString: "23 MINS",
        lastMileTravel: 0,
        slugs: {
          restaurant: "noto-healthy-ice-cream-koramangala-koramangala",
          city: "Bangalore",
        },
        cityState: "1",
        address: "",
        locality: "Ejipura",
        parentId: 7158,
        unserviceable: false,
        veg: true,
        select: false,
        favorite: false,
        tradeCampaignHeaders: [],
        aggregatedDiscountInfoV2: {
          header: "",
          shortDescriptionList: [],
          descriptionList: [],
          subHeader: "",
          headerType: 0,
          superFreedel: "",
        },
        chain: [],
        feeDetails: {
          fees: [
            {
              name: "BASE_TIME",
              fee: 0,
              message: "",
            },
            {
              name: "BASE_DISTANCE",
              fee: 8600,
              message: "",
            },
            {
              name: "ANCILLARY_SURGE_FEE",
              fee: 0,
              message: "",
            },
          ],
          totalFees: 8600,
          message: "",
          title: "Delivery Charge",
          amount: "8600",
          icon: "",
        },
        availability: {
          opened: true,
          nextOpenMessage: "",
          nextCloseMessage: "",
        },
        longDistanceEnabled: 0,
        rainMode: "NONE",
        thirdPartyAddress: false,
        thirdPartyVendor: "",
        adTrackingID:
          "cid=7617110~p=1~eid=00000189-a38f-69bd-12c7-a60d00520117~srvts=1690666232253~91153",
        badges: {
          imageBased: [],
          textBased: [],
          textExtendedBadges: [],
        },
        lastMileTravelString: "7.4 kms",
        hasSurge: false,
        cta: {
          link: "swiggy://menu?restaurant_id=408386",
          type: "DEEPLINK",
          text: "RESTAURANT_MENU",
        },
        sla: {
          restaurantId: "",
          deliveryTime: 23,
          minDeliveryTime: 23,
          maxDeliveryTime: 23,
          lastMileTravel: 0,
          lastMileDistance: 7.4,
          serviceability: "SERVICEABLE",
          rainMode: "NONE",
          preferentialService: false,
          iconType: "EMPTY",
        },
        promoted: true,
        avgRating: "4.3",
        totalRatings: 0,
        new: false,
      },
      subtype: "basic",
    },
    parentWidget: false,
  },
  {
    cardType: "restaurant",
    layoutAlignmentType: "VERTICAL",
    data: {
      type: "restaurant",
      data: {
        type: "F",
        id: "563199",
        name: "Rollsking",
        uuid: "deff3e2b-4a25-4c3b-8139-1741014396f9",
        city: "1",
        area: "JP Nagar",
        totalRatingsString: "",
        cloudinaryImageId: "cladupal7cobtvbg84mn",
        cuisines: ["North Indian", "Fast Food", "Beverages"],
        tags: [],
        costForTwo: 25000,
        costForTwoString: "₹250 FOR TWO",
        deliveryTime: 31,
        minDeliveryTime: 31,
        maxDeliveryTime: 31,
        slaString: "31 MINS",
        lastMileTravel: 0,
        slugs: {
          restaurant: "rolls-king-jp-nagar-jp-nagar",
          city: "Bangalore",
        },
        cityState: "1",
        address: "",
        locality: "7th Phase",
        parentId: 4697,
        unserviceable: false,
        veg: false,
        select: false,
        favorite: false,
        tradeCampaignHeaders: [],
        aggregatedDiscountInfoV2: {
          header: "",
          shortDescriptionList: [],
          descriptionList: [],
          subHeader: "",
          headerType: 0,
          superFreedel: "",
        },
        chain: [],
        feeDetails: {
          fees: [
            {
              name: "BASE_TIME",
              fee: 0,
              message: "",
            },
            {
              name: "BASE_DISTANCE",
              fee: 11600,
              message: "",
            },
            {
              name: "ANCILLARY_SURGE_FEE",
              fee: 0,
              message: "",
            },
          ],
          totalFees: 11600,
          message: "",
          title: "Delivery Charge",
          amount: "11600",
          icon: "",
        },
        availability: {
          opened: true,
          nextOpenMessage: "",
          nextCloseMessage: "",
        },
        longDistanceEnabled: 0,
        rainMode: "NONE",
        thirdPartyAddress: false,
        thirdPartyVendor: "",
        adTrackingID: "",
        badges: {
          imageBased: [],
          textBased: [],
          textExtendedBadges: [],
        },
        lastMileTravelString: "9.9 kms",
        hasSurge: false,
        cta: {
          link: "swiggy://menu?restaurant_id=563199",
          type: "DEEPLINK",
          text: "RESTAURANT_MENU",
        },
        sla: {
          restaurantId: "",
          deliveryTime: 31,
          minDeliveryTime: 31,
          maxDeliveryTime: 31,
          lastMileTravel: 0,
          lastMileDistance: 9.9,
          serviceability: "SERVICEABLE",
          rainMode: "NONE",
          preferentialService: false,
          iconType: "EMPTY",
        },
        promoted: false,
        avgRating: "4.0",
        totalRatings: 0,
        new: false,
      },
      subtype: "basic",
    },
    parentWidget: false,
  },
  {
    cardType: "restaurant",
    layoutAlignmentType: "VERTICAL",
    data: {
      type: "restaurant",
      data: {
        type: "F",
        id: "354939",
        name: "Shanghai House",
        uuid: "22034f4d-101e-4f4a-aa2a-e78809ebc5d3",
        city: "1",
        area: "Indiranagar",
        totalRatingsString: "",
        cloudinaryImageId: "f6wlizhxy4rp05qtqbom",
        cuisines: [
          "Chinese",
          "Thai",
          "Seafood",
          "Asian",
          "Healthy Food",
          "Beverages",
        ],
        tags: [],
        costForTwo: 40000,
        costForTwoString: "₹400 FOR TWO",
        deliveryTime: 34,
        minDeliveryTime: 34,
        maxDeliveryTime: 34,
        slaString: "34 MINS",
        lastMileTravel: 0,
        slugs: {
          restaurant: "chinese-bae-sector-50-sector-50",
          city: "Bangalore",
        },
        cityState: "1",
        address: "",
        locality: "1st Stage",
        parentId: 17040,
        unserviceable: false,
        veg: false,
        select: false,
        favorite: false,
        tradeCampaignHeaders: [],
        aggregatedDiscountInfoV2: {
          header: "",
          shortDescriptionList: [],
          descriptionList: [],
          subHeader: "",
          headerType: 0,
          superFreedel: "",
        },
        chain: [],
        feeDetails: {
          fees: [
            {
              name: "BASE_TIME",
              fee: 0,
              message: "",
            },
            {
              name: "BASE_DISTANCE",
              fee: 10100,
              message: "",
            },
            {
              name: "ANCILLARY_SURGE_FEE",
              fee: 0,
              message: "",
            },
          ],
          totalFees: 10100,
          message: "",
          title: "Delivery Charge",
          amount: "10100",
          icon: "",
        },
        availability: {
          opened: true,
          nextOpenMessage: "",
          nextCloseMessage: "",
        },
        longDistanceEnabled: 0,
        rainMode: "NONE",
        thirdPartyAddress: false,
        thirdPartyVendor: "",
        adTrackingID:
          "cid=7586742~p=3~eid=00000189-a38f-69bd-12c7-a60f0052036a~srvts=1690666232253~91153",
        badges: {
          imageBased: [],
          textBased: [],
          textExtendedBadges: [],
        },
        lastMileTravelString: "8.3 kms",
        hasSurge: false,
        cta: {
          link: "swiggy://menu?restaurant_id=354939",
          type: "DEEPLINK",
          text: "RESTAURANT_MENU",
        },
        sla: {
          restaurantId: "",
          deliveryTime: 34,
          minDeliveryTime: 34,
          maxDeliveryTime: 34,
          lastMileTravel: 0,
          lastMileDistance: 8.3,
          serviceability: "SERVICEABLE",
          rainMode: "NONE",
          preferentialService: false,
          iconType: "EMPTY",
        },
        promoted: true,
        avgRating: "3.8",
        totalRatings: 0,
        new: false,
      },
      subtype: "basic",
    },
    parentWidget: false,
  },
  {
    cardType: "restaurant",
    layoutAlignmentType: "VERTICAL",
    data: {
      type: "restaurant",
      data: {
        type: "F",
        id: "32603",
        name: "Leon's - Burgers & Wings (Leon Grill)",
        uuid: "aa86576d-1b82-41ac-9485-294a82e0a155",
        city: "1",
        area: "Indiranagar",
        totalRatingsString: "",
        cloudinaryImageId: "mtfco4meitoh97jynjxd",
        cuisines: [
          "American",
          "Snacks",
          "Turkish",
          "Portuguese",
          "Continental",
        ],
        tags: [],
        costForTwo: 30000,
        costForTwoString: "₹300 FOR TWO",
        deliveryTime: 26,
        minDeliveryTime: 26,
        maxDeliveryTime: 26,
        slaString: "26 MINS",
        lastMileTravel: 0,
        slugs: {
          restaurant: "leon-grill-indiranagar-indiranagar",
          city: "Bangalore",
        },
        cityState: "1",
        address: "",
        locality: "Indiranagar",
        parentId: 371281,
        unserviceable: false,
        veg: false,
        select: false,
        favorite: false,
        tradeCampaignHeaders: [],
        aggregatedDiscountInfoV2: {
          header: "",
          shortDescriptionList: [],
          descriptionList: [],
          subHeader: "",
          headerType: 0,
          superFreedel: "",
        },
        chain: [],
        feeDetails: {
          fees: [
            {
              name: "BASE_TIME",
              fee: 0,
              message: "",
            },
            {
              name: "BASE_DISTANCE",
              fee: 7600,
              message: "",
            },
            {
              name: "ANCILLARY_SURGE_FEE",
              fee: 0,
              message: "",
            },
          ],
          totalFees: 7600,
          message: "",
          title: "Delivery Charge",
          amount: "7600",
          icon: "",
        },
        availability: {
          opened: true,
          nextOpenMessage: "",
          nextCloseMessage: "",
        },
        longDistanceEnabled: 0,
        rainMode: "NONE",
        thirdPartyAddress: false,
        thirdPartyVendor: "",
        adTrackingID: "",
        badges: {
          imageBased: [],
          textBased: [],
          textExtendedBadges: [],
        },
        lastMileTravelString: "6 kms",
        hasSurge: false,
        cta: {
          link: "swiggy://menu?restaurant_id=32603",
          type: "DEEPLINK",
          text: "RESTAURANT_MENU",
        },
        sla: {
          restaurantId: "",
          deliveryTime: 26,
          minDeliveryTime: 26,
          maxDeliveryTime: 26,
          lastMileTravel: 0,
          lastMileDistance: 6,
          serviceability: "SERVICEABLE",
          rainMode: "NONE",
          preferentialService: false,
          iconType: "EMPTY",
        },
        promoted: false,
        avgRating: "4.3",
        totalRatings: 0,
        new: false,
      },
      subtype: "basic",
    },
    parentWidget: false,
  },
  {
    cardType: "restaurant",
    layoutAlignmentType: "VERTICAL",
    data: {
      type: "restaurant",
      data: {
        type: "F",
        id: "217048",
        name: "Chinese BAE",
        uuid: "f053c092-04d2-4551-b081-4449cf1a559f",
        city: "1",
        area: "BTM Layout",
        totalRatingsString: "",
        cloudinaryImageId: "n2lfnd2v4jf4x6l7rnos",
        cuisines: [
          "Chinese",
          "Thai",
          "Seafood",
          "Asian",
          "Combo",
          "Healthy Food",
          "Beverages",
        ],
        tags: [],
        costForTwo: 40000,
        costForTwoString: "₹400 FOR TWO",
        deliveryTime: 36,
        minDeliveryTime: 36,
        maxDeliveryTime: 36,
        slaString: "36 MINS",
        lastMileTravel: 0,
        slugs: {
          restaurant: "chinese-bae-btm-btm",
          city: "Bangalore",
        },
        cityState: "1",
        address: "",
        locality: "2nd Stage",
        parentId: 9769,
        unserviceable: false,
        veg: false,
        select: false,
        favorite: false,
        tradeCampaignHeaders: [],
        aggregatedDiscountInfoV2: {
          header: "",
          shortDescriptionList: [],
          descriptionList: [],
          subHeader: "",
          headerType: 0,
          superFreedel: "",
        },
        chain: [],
        feeDetails: {
          fees: [
            {
              name: "BASE_TIME",
              fee: 0,
              message: "",
            },
            {
              name: "BASE_DISTANCE",
              fee: 10100,
              message: "",
            },
            {
              name: "ANCILLARY_SURGE_FEE",
              fee: 0,
              message: "",
            },
          ],
          totalFees: 10100,
          message: "",
          title: "Delivery Charge",
          amount: "10100",
          icon: "",
        },
        availability: {
          opened: true,
          nextOpenMessage: "",
          nextCloseMessage: "",
        },
        longDistanceEnabled: 0,
        rainMode: "NONE",
        thirdPartyAddress: false,
        thirdPartyVendor: "",
        adTrackingID:
          "cid=7586739~p=4~eid=00000189-a38f-69bd-12c7-a61000520453~srvts=1690666232253~91153",
        badges: {
          imageBased: [],
          textBased: [],
          textExtendedBadges: [],
        },
        lastMileTravelString: "8.4 kms",
        hasSurge: false,
        cta: {
          link: "swiggy://menu?restaurant_id=217048",
          type: "DEEPLINK",
          text: "RESTAURANT_MENU",
        },
        sla: {
          restaurantId: "",
          deliveryTime: 36,
          minDeliveryTime: 36,
          maxDeliveryTime: 36,
          lastMileTravel: 0,
          lastMileDistance: 8.4,
          serviceability: "SERVICEABLE",
          rainMode: "NONE",
          preferentialService: false,
          iconType: "EMPTY",
        },
        promoted: true,
        avgRating: "3.9",
        totalRatings: 0,
        new: false,
      },
      subtype: "basic",
    },
    parentWidget: false,
  },
  {
    cardType: "restaurant",
    layoutAlignmentType: "VERTICAL",
    data: {
      type: "restaurant",
      data: {
        type: "F",
        id: "48581",
        name: "Rotti Walla",
        uuid: "5c2bbf06-7cc1-4f6b-9344-423d7130162e",
        city: "1",
        area: "Indiranagar",
        totalRatingsString: "",
        cloudinaryImageId: "kvlaq1ugkoozqr741zrv",
        cuisines: ["North Indian", "Chinese", "Snacks", "Beverages", "Tandoor"],
        tags: [],
        costForTwo: 20000,
        costForTwoString: "₹200 FOR TWO",
        deliveryTime: 28,
        minDeliveryTime: 28,
        maxDeliveryTime: 28,
        slaString: "28 MINS",
        lastMileTravel: 0,
        slugs: {
          restaurant: "tea-stories-indiranagar-indiranagar",
          city: "Bangalore",
        },
        cityState: "1",
        address: "",
        locality: "Appareddy Palya",
        parentId: 9541,
        unserviceable: false,
        veg: false,
        select: false,
        favorite: false,
        tradeCampaignHeaders: [],
        aggregatedDiscountInfoV2: {
          header: "",
          shortDescriptionList: [],
          descriptionList: [],
          subHeader: "",
          headerType: 0,
          superFreedel: "",
        },
        chain: [],
        feeDetails: {
          fees: [
            {
              name: "BASE_TIME",
              fee: 0,
              message: "",
            },
            {
              name: "BASE_DISTANCE",
              fee: 7600,
              message: "",
            },
            {
              name: "ANCILLARY_SURGE_FEE",
              fee: 0,
              message: "",
            },
          ],
          totalFees: 7600,
          message: "",
          title: "Delivery Charge",
          amount: "7600",
          icon: "",
        },
        availability: {
          opened: true,
          nextOpenMessage: "",
          nextCloseMessage: "",
        },
        longDistanceEnabled: 0,
        rainMode: "NONE",
        thirdPartyAddress: false,
        thirdPartyVendor: "",
        adTrackingID: "",
        badges: {
          imageBased: [],
          textBased: [],
          textExtendedBadges: [],
        },
        lastMileTravelString: "6.5 kms",
        hasSurge: false,
        cta: {
          link: "swiggy://menu?restaurant_id=48581",
          type: "DEEPLINK",
          text: "RESTAURANT_MENU",
        },
        sla: {
          restaurantId: "",
          deliveryTime: 28,
          minDeliveryTime: 28,
          maxDeliveryTime: 28,
          lastMileTravel: 0,
          lastMileDistance: 6.5,
          serviceability: "SERVICEABLE",
          rainMode: "NONE",
          preferentialService: false,
          iconType: "EMPTY",
        },
        promoted: false,
        avgRating: "3.9",
        totalRatings: 0,
        new: false,
      },
      subtype: "basic",
    },
    parentWidget: false,
  },
  {
    cardType: "restaurant",
    layoutAlignmentType: "VERTICAL",
    data: {
      type: "restaurant",
      data: {
        type: "F",
        id: "333566",
        name: "Momoz",
        uuid: "f4ece0b7-8eed-42bb-a09f-d105292db510",
        city: "1",
        area: "Indiranagar",
        totalRatingsString: "",
        cloudinaryImageId: "o3nvaund9vh2hq94arhy",
        cuisines: ["Chinese", "Thai", "Seafood", "Asian", "Malaysian"],
        tags: [],
        costForTwo: 35000,
        costForTwoString: "₹350 FOR TWO",
        deliveryTime: 32,
        minDeliveryTime: 32,
        maxDeliveryTime: 32,
        slaString: "32 MINS",
        lastMileTravel: 0,
        slugs: {
          restaurant: "momoz-indiranagar-indiranagar",
          city: "Bangalore",
        },
        cityState: "1",
        address: "",
        locality: "HAL 2ND STAGE",
        parentId: 2486,
        unserviceable: false,
        veg: false,
        select: false,
        favorite: false,
        tradeCampaignHeaders: [],
        aggregatedDiscountInfoV2: {
          header: "",
          shortDescriptionList: [],
          descriptionList: [],
          subHeader: "",
          headerType: 0,
          superFreedel: "",
        },
        chain: [],
        feeDetails: {
          fees: [
            {
              name: "BASE_DISTANCE",
              fee: 10100,
              message: "",
            },
            {
              name: "BASE_TIME",
              fee: 0,
              message: "",
            },
            {
              name: "ANCILLARY_SURGE_FEE",
              fee: 0,
              message: "",
            },
          ],
          totalFees: 10100,
          message: "",
          title: "Delivery Charge",
          amount: "10100",
          icon: "",
        },
        availability: {
          opened: true,
          nextOpenMessage: "",
          nextCloseMessage: "",
        },
        longDistanceEnabled: 0,
        rainMode: "NONE",
        thirdPartyAddress: false,
        thirdPartyVendor: "",
        adTrackingID:
          "cid=7586740~p=5~eid=00000189-a38f-69bd-12c7-a61100520506~srvts=1690666232253~91153",
        badges: {
          imageBased: [],
          textBased: [],
          textExtendedBadges: [],
        },
        lastMileTravelString: "8.3 kms",
        hasSurge: false,
        cta: {
          link: "swiggy://menu?restaurant_id=333566",
          type: "DEEPLINK",
          text: "RESTAURANT_MENU",
        },
        sla: {
          restaurantId: "",
          deliveryTime: 32,
          minDeliveryTime: 32,
          maxDeliveryTime: 32,
          lastMileTravel: 0,
          lastMileDistance: 8.3,
          serviceability: "SERVICEABLE",
          rainMode: "NONE",
          preferentialService: false,
          iconType: "EMPTY",
        },
        promoted: true,
        avgRating: "3.9",
        totalRatings: 0,
        new: false,
      },
      subtype: "basic",
    },
    parentWidget: false,
  },
  {
    cardType: "restaurant",
    layoutAlignmentType: "VERTICAL",
    data: {
      type: "restaurant",
      data: {
        type: "F",
        id: "59627",
        name: "La Pino'z Pizza",
        uuid: "c9b0898a-97c5-4e08-8558-f9bd493b6b27",
        city: "1",
        area: "Koramangala",
        totalRatingsString: "",
        cloudinaryImageId: "ntjshqsv2k7vxtv7vmib",
        cuisines: ["Pizzas", "Pastas", "Italian", "Desserts", "Beverages"],
        tags: [],
        costForTwo: 25100,
        costForTwoString: "₹251 FOR TWO",
        deliveryTime: 32,
        minDeliveryTime: 32,
        maxDeliveryTime: 32,
        slaString: "32 MINS",
        lastMileTravel: 0,
        slugs: {
          restaurant: "la-pinoz-pizza-koramangala-koramangala",
          city: "Bangalore",
        },
        cityState: "1",
        address: "",
        locality: "Koramangala",
        parentId: 4961,
        unserviceable: false,
        veg: false,
        select: false,
        favorite: false,
        tradeCampaignHeaders: [],
        aggregatedDiscountInfoV2: {
          header: "",
          shortDescriptionList: [],
          descriptionList: [],
          subHeader: "",
          headerType: 0,
          superFreedel: "",
        },
        chain: [],
        feeDetails: {
          fees: [
            {
              name: "BASE_DISTANCE",
              fee: 8600,
              message: "",
            },
            {
              name: "BASE_TIME",
              fee: 0,
              message: "",
            },
            {
              name: "ANCILLARY_SURGE_FEE",
              fee: 0,
              message: "",
            },
          ],
          totalFees: 8600,
          message: "",
          title: "Delivery Charge",
          amount: "8600",
          icon: "",
        },
        availability: {
          opened: true,
          nextOpenMessage: "",
          nextCloseMessage: "",
        },
        longDistanceEnabled: 0,
        rainMode: "NONE",
        thirdPartyAddress: false,
        thirdPartyVendor: "",
        adTrackingID: "",
        badges: {
          imageBased: [],
          textBased: [],
          textExtendedBadges: [],
        },
        lastMileTravelString: "8 kms",
        hasSurge: false,
        cta: {
          link: "swiggy://menu?restaurant_id=59627",
          type: "DEEPLINK",
          text: "RESTAURANT_MENU",
        },
        sla: {
          restaurantId: "",
          deliveryTime: 32,
          minDeliveryTime: 32,
          maxDeliveryTime: 32,
          lastMileTravel: 0,
          lastMileDistance: 8,
          serviceability: "SERVICEABLE",
          rainMode: "NONE",
          preferentialService: false,
          iconType: "EMPTY",
        },
        promoted: false,
        avgRating: "4.1",
        totalRatings: 0,
        new: false,
      },
      subtype: "basic",
    },
    parentWidget: false,
  },
  {
    cardType: "restaurant",
    layoutAlignmentType: "VERTICAL",
    data: {
      type: "restaurant",
      data: {
        type: "F",
        id: "531381",
        name: "Olio - The Wood Fired Pizzeria",
        uuid: "7e08c07e-9b5d-4bbf-875b-7f197b30b81a",
        city: "1",
        area: "Indiranagar",
        totalRatingsString: "",
        cloudinaryImageId: "tergaeovicova1ntvbyn",
        cuisines: ["Pizzas", "Italian"],
        tags: [],
        costForTwo: 30000,
        costForTwoString: "₹300 FOR TWO",
        deliveryTime: 61,
        minDeliveryTime: 61,
        maxDeliveryTime: 61,
        slaString: "61 MINS",
        lastMileTravel: 0,
        slugs: {
          restaurant:
            "olio-the-wood-fired-pizzeria-3rd-b-crosssector-yelahanka",
          city: "Bangalore",
        },
        cityState: "1",
        address: "",
        locality: "CMH Road",
        parentId: 11633,
        unserviceable: false,
        veg: false,
        select: false,
        favorite: false,
        tradeCampaignHeaders: [],
        aggregatedDiscountInfoV2: {
          header: "",
          shortDescriptionList: [],
          descriptionList: [],
          subHeader: "",
          headerType: 0,
          superFreedel: "",
        },
        chain: [],
        feeDetails: {
          fees: [
            {
              name: "BASE_DISTANCE",
              fee: 7600,
              message: "",
            },
            {
              name: "BASE_TIME",
              fee: 0,
              message: "",
            },
            {
              name: "ANCILLARY_SURGE_FEE",
              fee: 0,
              message: "",
            },
          ],
          totalFees: 7600,
          message: "",
          title: "Delivery Charge",
          amount: "7600",
          icon: "",
        },
        availability: {
          opened: true,
          nextOpenMessage: "",
          nextCloseMessage: "",
        },
        longDistanceEnabled: 0,
        rainMode: "NONE",
        thirdPartyAddress: false,
        thirdPartyVendor: "",
        adTrackingID:
          "cid=7564733~p=6~eid=00000189-a38f-69bd-12c7-a6120052064d~srvts=1690666232253~91153",
        badges: {
          imageBased: [],
          textBased: [],
          textExtendedBadges: [],
        },
        lastMileTravelString: "6.8 kms",
        hasSurge: false,
        cta: {
          link: "swiggy://menu?restaurant_id=531381",
          type: "DEEPLINK",
          text: "RESTAURANT_MENU",
        },
        sla: {
          restaurantId: "",
          deliveryTime: 61,
          minDeliveryTime: 61,
          maxDeliveryTime: 61,
          lastMileTravel: 0,
          lastMileDistance: 6.8,
          serviceability: "SERVICEABLE",
          rainMode: "NONE",
          preferentialService: false,
          iconType: "EMPTY",
        },
        promoted: true,
        avgRating: "4.1",
        totalRatings: 0,
        new: false,
      },
      subtype: "basic",
    },
    parentWidget: false,
  },
  {
    cardType: "restaurant",
    layoutAlignmentType: "VERTICAL",
    data: {
      type: "restaurant",
      data: {
        type: "F",
        id: "577017",
        name: "Crispy Studio",
        uuid: "58ba3362-8206-4ca8-ac75-b105cb51f231",
        city: "1",
        area: "JP Nagar",
        totalRatingsString: "",
        cloudinaryImageId: "ioqg6ynikepkzqcq5gue",
        cuisines: [
          "Burgers",
          "Biryani",
          "American",
          "Turkish",
          "Salads",
          "Fast Food",
        ],
        tags: [],
        costForTwo: 40000,
        costForTwoString: "₹400 FOR TWO",
        deliveryTime: 30,
        minDeliveryTime: 30,
        maxDeliveryTime: 30,
        slaString: "30 MINS",
        lastMileTravel: 0,
        slugs: {
          restaurant: "crispy-studio-jp-nagar-jp-nagar",
          city: "Bangalore",
        },
        cityState: "1",
        address: "",
        locality: "5th Phase",
        parentId: 345614,
        unserviceable: false,
        veg: false,
        select: false,
        favorite: false,
        tradeCampaignHeaders: [],
        aggregatedDiscountInfoV2: {
          header: "",
          shortDescriptionList: [],
          descriptionList: [],
          subHeader: "",
          headerType: 0,
          superFreedel: "",
        },
        chain: [],
        feeDetails: {
          fees: [
            {
              name: "BASE_TIME",
              fee: 0,
              message: "",
            },
            {
              name: "BASE_DISTANCE",
              fee: 11600,
              message: "",
            },
            {
              name: "ANCILLARY_SURGE_FEE",
              fee: 0,
              message: "",
            },
          ],
          totalFees: 11600,
          message: "",
          title: "Delivery Charge",
          amount: "11600",
          icon: "",
        },
        availability: {
          opened: true,
          nextOpenMessage: "",
          nextCloseMessage: "",
        },
        longDistanceEnabled: 0,
        rainMode: "NONE",
        thirdPartyAddress: false,
        thirdPartyVendor: "",
        adTrackingID: "",
        badges: {
          imageBased: [],
          textBased: [],
          textExtendedBadges: [],
        },
        lastMileTravelString: "9.9 kms",
        hasSurge: false,
        cta: {
          link: "swiggy://menu?restaurant_id=577017",
          type: "DEEPLINK",
          text: "RESTAURANT_MENU",
        },
        sla: {
          restaurantId: "",
          deliveryTime: 30,
          minDeliveryTime: 30,
          maxDeliveryTime: 30,
          lastMileTravel: 0,
          lastMileDistance: 9.9,
          serviceability: "SERVICEABLE",
          rainMode: "NONE",
          preferentialService: false,
          iconType: "EMPTY",
        },
        promoted: false,
        avgRating: "4.3",
        totalRatings: 0,
        new: false,
      },
      subtype: "basic",
    },
    parentWidget: false,
  },
  {
    cardType: "restaurant",
    layoutAlignmentType: "VERTICAL",
    data: {
      type: "restaurant",
      data: {
        type: "F",
        id: "63381",
        name: "Keventers - Milkshakes & Desserts",
        uuid: "52fa7a56-eb4e-48fc-842f-85424c1c1ff6",
        city: "1",
        area: "Koramangala",
        totalRatingsString: "",
        cloudinaryImageId: "f0e94c984813053f46c214f18ce73d59",
        cuisines: ["Beverages", "Ice Cream", "Desserts", "Healthy Food"],
        tags: [],
        costForTwo: 20000,
        costForTwoString: "₹200 FOR TWO",
        deliveryTime: 27,
        minDeliveryTime: 27,
        maxDeliveryTime: 27,
        slaString: "27 MINS",
        lastMileTravel: 0,
        slugs: {
          restaurant: "keventers-forum-mall-adugodi-btm",
          city: "Bangalore",
        },
        cityState: "1",
        address: "",
        locality: "7th Block",
        parentId: 268997,
        unserviceable: false,
        veg: true,
        select: false,
        favorite: false,
        tradeCampaignHeaders: [],
        aggregatedDiscountInfoV2: {
          header: "",
          shortDescriptionList: [],
          descriptionList: [],
          subHeader: "",
          headerType: 0,
          superFreedel: "",
        },
        chain: [],
        feeDetails: {
          fees: [
            {
              name: "BASE_DISTANCE",
              fee: 7600,
              message: "",
            },
            {
              name: "BASE_TIME",
              fee: 0,
              message: "",
            },
            {
              name: "ANCILLARY_SURGE_FEE",
              fee: 0,
              message: "",
            },
          ],
          totalFees: 7600,
          message: "",
          title: "Delivery Charge",
          amount: "7600",
          icon: "",
        },
        availability: {
          opened: true,
          nextOpenMessage: "",
          nextCloseMessage: "",
        },
        longDistanceEnabled: 0,
        rainMode: "NONE",
        thirdPartyAddress: false,
        thirdPartyVendor: "",
        adTrackingID:
          "cid=7544464~p=7~eid=00000189-a38f-69bd-12c7-a61300520708~srvts=1690666232253~91153",
        badges: {
          imageBased: [],
          textBased: [],
          textExtendedBadges: [],
        },
        lastMileTravelString: "6.5 kms",
        hasSurge: false,
        cta: {
          link: "swiggy://menu?restaurant_id=63381",
          type: "DEEPLINK",
          text: "RESTAURANT_MENU",
        },
        sla: {
          restaurantId: "",
          deliveryTime: 27,
          minDeliveryTime: 27,
          maxDeliveryTime: 27,
          lastMileTravel: 0,
          lastMileDistance: 6.5,
          serviceability: "SERVICEABLE",
          rainMode: "NONE",
          preferentialService: false,
          iconType: "EMPTY",
        },
        promoted: true,
        avgRating: "4.2",
        totalRatings: 0,
        new: false,
      },
      subtype: "basic",
    },
    parentWidget: false,
  },
  {
    cardType: "restaurant",
    layoutAlignmentType: "VERTICAL",
    data: {
      type: "restaurant",
      data: {
        type: "F",
        id: "139114",
        name: "Main Lassi Shop",
        uuid: "0b14e194-a6ef-4174-872c-a29c8d38c4a0",
        city: "1",
        area: "Central Bangalore",
        totalRatingsString: "",
        cloudinaryImageId: "cxil95w4fbwvqmtjtmbn",
        cuisines: ["Beverages", "Juices", "Ice Cream", "Pizzas", "Desserts"],
        tags: [],
        costForTwo: 25000,
        costForTwoString: "₹250 FOR TWO",
        deliveryTime: 20,
        minDeliveryTime: 20,
        maxDeliveryTime: 20,
        slaString: "20 MINS",
        lastMileTravel: 0,
        slugs: {
          restaurant: "savera-lassi-shop-bangalore-frazer-town",
          city: "Bangalore",
        },
        cityState: "1",
        address: "",
        locality: "Shivajinagar,NO 55 COCKBURN ROAD",
        parentId: 20112,
        unserviceable: false,
        veg: false,
        select: false,
        favorite: false,
        tradeCampaignHeaders: [],
        aggregatedDiscountInfoV2: {
          header: "",
          shortDescriptionList: [],
          descriptionList: [],
          subHeader: "",
          headerType: 0,
          superFreedel: "",
        },
        chain: [],
        feeDetails: {
          fees: [
            {
              name: "BASE_TIME",
              fee: 0,
              message: "",
            },
            {
              name: "BASE_DISTANCE",
              fee: 4100,
              message: "",
            },
            {
              name: "ANCILLARY_SURGE_FEE",
              fee: 0,
              message: "",
            },
          ],
          totalFees: 4100,
          message: "",
          title: "Delivery Charge",
          amount: "4100",
          icon: "",
        },
        availability: {
          opened: true,
          nextOpenMessage: "",
          nextCloseMessage: "",
        },
        longDistanceEnabled: 0,
        rainMode: "NONE",
        thirdPartyAddress: false,
        thirdPartyVendor: "",
        adTrackingID: "",
        badges: {
          imageBased: [],
          textBased: [],
          textExtendedBadges: [],
        },
        lastMileTravelString: "3 kms",
        hasSurge: false,
        cta: {
          link: "swiggy://menu?restaurant_id=139114",
          type: "DEEPLINK",
          text: "RESTAURANT_MENU",
        },
        sla: {
          restaurantId: "",
          deliveryTime: 20,
          minDeliveryTime: 20,
          maxDeliveryTime: 20,
          lastMileTravel: 0,
          lastMileDistance: 3,
          serviceability: "SERVICEABLE",
          rainMode: "NONE",
          preferentialService: false,
          iconType: "EMPTY",
        },
        promoted: false,
        avgRating: "3.8",
        totalRatings: 0,
        new: false,
      },
      subtype: "basic",
    },
    parentWidget: false,
  },
  {
    cardType: "restaurant",
    layoutAlignmentType: "VERTICAL",
    data: {
      type: "restaurant",
      data: {
        type: "F",
        id: "442032",
        name: "Keventers Ice Cream",
        uuid: "7d96e3c1-d746-4024-942c-8f40185d7af0",
        city: "1",
        area: "Koramangala",
        totalRatingsString: "",
        cloudinaryImageId: "462885ba9eb56bddf68bf3c89963b3c7",
        cuisines: ["Ice Cream", "Desserts"],
        tags: [],
        costForTwo: 20000,
        costForTwoString: "₹200 FOR TWO",
        deliveryTime: 23,
        minDeliveryTime: 23,
        maxDeliveryTime: 23,
        slaString: "23 MINS",
        lastMileTravel: 0,
        slugs: {
          restaurant: "keventers-ice-creamery-7th-block-koramangala",
          city: "Bangalore",
        },
        cityState: "1",
        address: "",
        locality: "7th Block",
        parentId: 272044,
        unserviceable: false,
        veg: true,
        select: false,
        favorite: false,
        tradeCampaignHeaders: [],
        aggregatedDiscountInfoV2: {
          header: "",
          shortDescriptionList: [],
          descriptionList: [],
          subHeader: "",
          headerType: 0,
          superFreedel: "",
        },
        chain: [],
        feeDetails: {
          fees: [
            {
              name: "BASE_DISTANCE",
              fee: 7600,
              message: "",
            },
            {
              name: "BASE_TIME",
              fee: 0,
              message: "",
            },
            {
              name: "ANCILLARY_SURGE_FEE",
              fee: 0,
              message: "",
            },
          ],
          totalFees: 7600,
          message: "",
          title: "Delivery Charge",
          amount: "7600",
          icon: "",
        },
        availability: {
          opened: true,
          nextOpenMessage: "",
          nextCloseMessage: "",
        },
        longDistanceEnabled: 0,
        rainMode: "NONE",
        thirdPartyAddress: false,
        thirdPartyVendor: "",
        adTrackingID:
          "cid=7544457~p=9~eid=00000189-a38f-69bd-12c7-a61500520906~srvts=1690666232253~91153",
        badges: {
          imageBased: [],
          textBased: [],
          textExtendedBadges: [
            {
              iconId: "guiltfree/GF_Logo_android_3x",
              description: "",
              shortDescription: "options available",
              fontColor: "#7E808C",
            },
          ],
        },
        lastMileTravelString: "6.5 kms",
        hasSurge: false,
        cta: {
          link: "swiggy://menu?restaurant_id=442032",
          type: "DEEPLINK",
          text: "RESTAURANT_MENU",
        },
        sla: {
          restaurantId: "",
          deliveryTime: 23,
          minDeliveryTime: 23,
          maxDeliveryTime: 23,
          lastMileTravel: 0,
          lastMileDistance: 6.5,
          serviceability: "SERVICEABLE",
          rainMode: "NONE",
          preferentialService: false,
          iconType: "EMPTY",
        },
        promoted: true,
        avgRating: "4.2",
        totalRatings: 0,
        new: false,
      },
      subtype: "basic",
    },
    parentWidget: false,
  },
  {
    cardType: "restaurant",
    layoutAlignmentType: "VERTICAL",
    data: {
      type: "restaurant",
      data: {
        type: "F",
        id: "291456",
        name: "The Fritter Company",
        uuid: "8ef87f7f-694c-431e-80ac-6490ea9c0902",
        city: "1",
        area: "Btm Layout",
        totalRatingsString: "",
        cloudinaryImageId: "3660c857274de528702f316b4a7a1996",
        cuisines: [
          "Burgers",
          "American",
          "Salads",
          "Snacks",
          "Desserts",
          "Fast Food",
          "Continental",
        ],
        tags: [],
        costForTwo: 20000,
        costForTwoString: "₹200 FOR TWO",
        deliveryTime: 31,
        minDeliveryTime: 31,
        maxDeliveryTime: 31,
        slaString: "31 MINS",
        lastMileTravel: 0,
        slugs: {
          restaurant: "the-fritter-company-btm-btm-2",
          city: "Bangalore",
        },
        cityState: "1",
        address: "",
        locality: "2nd Stage",
        parentId: 21135,
        unserviceable: false,
        veg: false,
        select: false,
        favorite: false,
        tradeCampaignHeaders: [],
        aggregatedDiscountInfoV2: {
          header: "",
          shortDescriptionList: [],
          descriptionList: [],
          subHeader: "",
          headerType: 0,
          superFreedel: "",
        },
        chain: [],
        feeDetails: {
          fees: [
            {
              name: "BASE_TIME",
              fee: 0,
              message: "",
            },
            {
              name: "BASE_DISTANCE",
              fee: 11600,
              message: "",
            },
            {
              name: "ANCILLARY_SURGE_FEE",
              fee: 0,
              message: "",
            },
          ],
          totalFees: 11600,
          message: "",
          title: "Delivery Charge",
          amount: "11600",
          icon: "",
        },
        availability: {
          opened: true,
          nextOpenMessage: "",
          nextCloseMessage: "",
        },
        longDistanceEnabled: 0,
        rainMode: "NONE",
        thirdPartyAddress: false,
        thirdPartyVendor: "",
        adTrackingID: "",
        badges: {
          imageBased: [],
          textBased: [],
          textExtendedBadges: [],
        },
        lastMileTravelString: "9.2 kms",
        hasSurge: false,
        cta: {
          link: "swiggy://menu?restaurant_id=291456",
          type: "DEEPLINK",
          text: "RESTAURANT_MENU",
        },
        sla: {
          restaurantId: "",
          deliveryTime: 31,
          minDeliveryTime: 31,
          maxDeliveryTime: 31,
          lastMileTravel: 0,
          lastMileDistance: 9.2,
          serviceability: "SERVICEABLE",
          rainMode: "NONE",
          preferentialService: false,
          iconType: "EMPTY",
        },
        promoted: false,
        avgRating: "4.2",
        totalRatings: 0,
        new: false,
      },
      subtype: "basic",
    },
    parentWidget: false,
  },
];
